export const foodNames = [
	'Spaghetti Carbonara',
	'Chicken Alfredo',
	'Beef Stroganoff',
	'Margherita Pizza',
	'Sushi Rolls',
	'Pad Thai',
	'Caesar Salad',
	'Chicken Parmesan',
	'Chocolate Chip Cookies',
	'Tiramisu',
	'Guacamole',
	'Baked Ziti',
	'Lobster Bisque',
	'Miso Soup',
	'Chicken Fajitas',
	'Shrimp Scampi',
	'Clam Chowder',
	'Beef Tacos',
	'Greek Salad',
	'Beef and Broccoli',
	'Buffalo Wings',
	'Pho Soup',
	'Eggplant Parmesan',
	'Gumbo',
	'Chocolate Fondue',
	'Teriyaki Chicken',
	'Margarita',
	'Blueberry Pancakes',
	'Lobster Roll',
	'Caprese Salad',
	'Chicken Quesadilla',
	'Creme Brulee',
	'Vegetable Stir-Fry',
	'Chicken Marsala',
	'Pesto Pasta',
	'Chicken and Waffles',
	'Shrimp Cocktail',
	'Beef Burrito',
	'French Onion Soup',
	'Beef and Noodle Soup',
	'Apple Pie',
	'Chicken Shawarma',
	'Ratatouille',
	'Crab Cakes',
	'Pumpkin Soup',
	'Caesar Wrap',
	'Beef and Cheddar Sandwich',
	'Quiche Lorraine',
	'Philly Cheesesteak',
	'Baked Potato',
	'Raspberry Sorbet',
	'Teriyaki Salmon',
	'Chicken Teriyaki Bowl',
	'Chocolate Mousse',
	'Beef and Spinach Salad',
	'Chicken Caesar Wrap',
	'Beef and Guinness Stew',
	'Pineapple Fried Rice',
	'Oyster Rockefeller',
	'Chicken Pot Pie',
	'Beef and Peppers Stir-Fry',
	'Blueberry Muffins',
	'Vegetable Lasagna',
	'Tomato Basil Soup',
	'Beef and Rice Casserole',
	'Beef and Broccoli Stir-Fry',
	'Chocolate Covered Strawberries',
	'Chicken and Rice Soup',
	'Cheeseburger',
	'Chicken and Dumplings',
	'Apple Crisp',
	'Clam Linguine',
	'Beef and Potato Hash',
	'Lemon Bars',
	'Chicken Fettuccine Alfredo',
	'Beef and Cabbage Rolls',
	'Tuna Salad Sandwich',
	'Cheese Fries',
	'Chicken Enchiladas',
	'Spinach and Artichoke Dip',
	'Mango Salsa',
	'Beef and Black Bean Tacos',
	'Crab Rangoon',
	'Chicken and Rice Casserole',
	'Peanut Butter and Jelly Sandwich',
	'Beef and Onion Pie',
	'Shrimp and Grits',
	'Beef and Barley Soup',
	'Apple Turnover',
	'Chicken Cordon Bleu',
	'Baked Alaska',
	'Beef and Cheese Quesadilla',
	'Nachos',
	'Chicken and Mushroom Risotto',
	'Chocolate Eclairs'
];
